- hosts: edge-1
  gather_facts: no
  vars:
    wg_core_address: "{{ lookup('env','WG_CORE_ADDRESS') }}"
    wg_edge_1_address: "{{ lookup('env','WG_EDGE_1_ADDRESS') }}"
    lan_edge_1_network: "{{ lookup('env','LAN_EDGE_1_NETWORK') }}"
    lan_mask: "{{ lookup('env','LAN_MASK') }}"
    bgp_as: "{{ lookup('env','BGP_AS') }}"

  tasks:
    - name: Configure BGP on edge-1
      vyos.vyos.vyos_config:
        lines:
          - "set protocols bgp system-as {{ bgp_as }}"
          - "set protocols bgp parameters router-id {{ wg_edge_1_address }}"
          - "set protocols bgp neighbor {{ wg_core_address }} remote-as {{ bgp_as }}"

          - "set protocols bgp network {{ lan_edge_1_network }}/{{ lan_mask }}"

        save: true
