- hosts: "{{ host }}"
  gather_facts: no
  tasks:
    - name: "View qos on {{ host }}"
      vyos.vyos.vyos_command:
        commands:
          - show configuration json
      register: cfg_json
    - debug:
        var: cfg_json.stdout[0]
    - set_fact:
        vyos_config: "{{ cfg_json.stdout[0] | from_json }}"

    - debug:
        var: vyos_config.qos
