- hosts: "{{ host }}"
  gather_facts: no
  tasks:
    - name: "Add shaper '{{ name }}' on {{ host }} interface : {{ interface }}"
      vyos.vyos.vyos_config:
        lines:
          - "set qos policy shaper '{{ name }}' default bandwidth {{ rate }}mbit"
          - "set qos interface {{ interface }} egress '{{ name }}'"
        save: true
