- hosts: "{{ host }}"
  gather_facts: no
  tasks:
    - name: "Removing all firewall rules on {{ inventory_hostname }}"
      vyos.vyos.vyos_config:
        lines:
          - "delete firewall"
        save: true
