- hosts: "{{ host }}"
  gather_facts: no
  tasks:
    - name: "Remove DSCP marking on {{ host }} interface : {{ interface }}"
      vyos.vyos.vyos_config:
        lines:
          - "delete interfaces ethernet {{ interface }} firewall in name MARK"
          - "delete firewall ipv4 name MARK"
        save: true
