- hosts: "{{ host }}"
  gather_facts: no
  tasks:
    - name: "Remove shaper 'SHAPERDSCP' on {{ host }} interface {{ interface }}"
      vyos.vyos.vyos_config:
        lines:
          - "delete qos interface {{ interface }} egress SHAPERDSCP"
          - "delete qos policy shaper SHAPERDSCP"

        save: true
