- hosts: "{{ host }}"
  gather_facts: no
  tasks:
    - name: "Removing limiter '{{ name }}' on {{ inventory_hostname }} interface : {{ interface }}"
      vyos.vyos.vyos_config:
        lines:
          - "delete qos interface {{ interface }} ingress '{{ name }}'"
          - "delete qos policy limiter '{{ name }}'"
        save: true
