- hosts: "{{ host }}"
  gather_facts: no
  tasks:
    - name: "Removing shaper '{{ name }}' on {{ inventory_hostname }} interface : {{ interface }}"
      vyos.vyos.vyos_config:
        lines:
          - "delete qos interface {{ interface }} egress '{{ name }}'"
          - "delete qos policy shaper '{{ name }}'"
        save: true
