- hosts: "{{ host }}"
  gather_facts: no
  tasks:
    - name: Remove DSCP marking rules on {{ inventory_hostname }}
      vyos.vyos.vyos_config:
        lines:
          - "delete firewall ipv4 forward filter rule 10"
          - "delete firewall ipv4 forward filter rule 20"
          - "delete firewall ipv4 forward filter rule 30"
          - "delete firewall ipv4 forward filter rule 40"
        save: true
