- hosts: "{{ host }}"
  gather_facts: no
  ignore_unreachable: yes

  tasks:
    - name: "Removing all firewall rules on {{ inventory_hostname }}"
      vyos.vyos.vyos_config:
        lines:
          - "delete firewall"
        save: true
      ignore_errors: yes
